homepage: "https://www.qubes-os.org/"
language: c++
primary_contact: "jpo@vt.edu"
auto_ccs:
 - "joanna@invisiblethingslab.com"
 - "marmarek@invisiblethingslab.com"
 - "paras.chetal@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - undefined
  - dataflow
architectures:
  - x86_64
  - i386
